In [27]:
import dance
import dancer_points as dp
from datetime import date
import numpy as np
import sys
np.set_printoptions(linewidth=sys.maxsize)

In [34]:
testdate = date(2023, 9, 5)
today = date.today()
(today - testdate).days

368

In [38]:
first_comp_date = ("09", "07", "2024")
month, day, year = map(int, first_comp_date)
print(date(year, month, day) - date.today())

0:00:00


In [16]:
# test_pts = dp.Points()
# syl = test_pts.syllabus_data
# op = test_pts.open_data
syl = np.random.randint(0, high=99, size=(4, 19))
op = np.random.randint(0, high=99, size=(3, 4))
test_pts = dp.Points(syl, op)

In [17]:
print("Syllabus")
print(syl)
print("Open")
print(op)
print()
# print(test_pts)

Syllabus
[[67  8 41 52  0  6  7 49 56 55  9 28  8 69 65 76 86 92 93]
 [38 61 88 39 92 93 30 44  6 50 92 25 16 27 11 25 47 24 26]
 [ 6 82 47 86 23 55 52 91 10 82 83 88 70 42 37 69 68 23 82]
 [50 29 71 56 67 32 40  7 55 48 27 92 39 82 23 27  4 91 21]]
Open
[[83 58 76 64]
 [56 90 70 17]
 [33 74 93 50]]



In [18]:
str(syl[0][:5])[1:-1]

'67  8 41 52  0'

In [19]:
print("Standard")
print(test_pts.standard()[0])
print()
print(test_pts.standard()[0])
print()
print("Smooth")
print(test_pts.smooth()[0])
print()
print(test_pts.smooth()[1])
print()
print("Latin")
print(test_pts.latin()[0])
print()
print(test_pts.latin()[1])
print()
print("Rhythm")
print(test_pts.rhythm()[0])
print()
print(test_pts.rhythm()[1])

Standard
[[67  8 41 52  0]
 [38 61 88 39 92]
 [ 6 82 47 86 23]
 [50 29 71 56 67]]

[[67  8 41 52  0]
 [38 61 88 39 92]
 [ 6 82 47 86 23]
 [50 29 71 56 67]]

Smooth
[[ 6  7 49 56]
 [93 30 44  6]
 [55 52 91 10]
 [32 40  7 55]]

[[58]
 [90]
 [74]]

Latin
[[55  9 28  8 69]
 [50 92 25 16 27]
 [82 83 88 70 42]
 [48 27 92 39 82]]

[[76]
 [70]
 [93]]

Rhythm
[[65 76 86 92 93]
 [11 25 47 24 26]
 [37 69 68 23 82]
 [23 27  4 91 21]]

[[64]
 [17]
 [50]]


In [20]:
lin_data = test_pts.linear_data()
for offset in [0, 19, 38, 57, 76, 80, 84]:
    if offset < 76:
        for start, end in [(0, 5), (5, 9), (9, 14), (14, 19)]:
            print(str(lin_data[offset + start:offset + end])[1:-1])
    else:
        for i in range(4):
            print(str(lin_data[offset + i:offset + i + 1])[1:-1])

67  8 41 52  0
 6  7 49 56
55  9 28  8 69
65 76 86 92 93
38 61 88 39 92
93 30 44  6
50 92 25 16 27
11 25 47 24 26
 6 82 47 86 23
55 52 91 10
82 83 88 70 42
37 69 68 23 82
50 29 71 56 67
32 40  7 55
48 27 92 39 82
23 27  4 91 21
83
58
76
64
56
90
70
17
33
74
93
50


In [21]:
print(test_pts)

                     Standard      |  Smooth     |  Latin         |  Rhythm        |
                     W  T  V  F  Q |  W  T  F  V |  C  S  R  P  J |  C  R  S  B  M |
          Newcomer  67  8 41 52  0 |  6  7 49 56 | 55  9 28  8 69 | 65 76 86 92 93 |
            Bronze  38 61 88 39 92 | 93 30 44  6 | 50 92 25 16 27 | 11 25 47 24 26 |
            Silver   6 82 47 86 23 | 55 52 91 10 | 82 83 88 70 42 | 37 69 68 23 82 |
              Gold  50 29 71 56 67 | 32 40  7 55 | 48 27 92 39 82 | 23 27  4 91 21 |
            Novice        83       |      58     |       76       |       64       |
          Prechamp        56       |      90     |       70       |       17       |
             Champ        33       |      74     |       93       |       50       |
        
